# 버전 정의
# 버전에 따라서 지원하는 형식이 다릅니다.
version: '3.0'

# service 정의
# docker-compose로 생성 할 container의 옵션을 정의 합니다.
# service안의 container들은 하나의 project로서 docker-compose로 관리 됩니다.
services:
    #생성 할 container 이름을 지정 합니다.
    container-backend:
        #container 생성시 사용 할 이미지 지정
        image: testbackend:latest
        #build 옵션
        # docker-compose build 옵션에서 사용 됩니다.
        # dockerfile에 명시된 FROM의 image를 사용하여 위에 명시된image 이름과 tag로 새로운 image를 생성 합니다.
        build:
            #dockerfile의 위치를 지정 합니다.
            context: ./backend
        #container port mapping 정보
        ports:
            - "8080:8080"
        #EXPOSE
        # 도커 컨테이너가 실행되었을 때 요청을 기다리고 있는(Listen) 포트를 지정합니다. 여러개의 포트를 지정할 수 있습니다.
        expose:
            - "8080"
        #환경 변수 리스트를 정의
        #실행 환경 설정

    container-frontend:
        image: testfrontend:latest
        build:
            context: ./frontend
        ports:
            - "80:80"
        expose:
            - "80"
        depends_on:
            - container-backend
        restart: always
